name: CI pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  build-test-plan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: pip install -r app/requirements.txt

    - name: Run tests
      run: pytest

    - name: Build Lambda Package
      working-directory: app
      run: |
        rm -rf package && mkdir package
        pip install -r requirements.txt -t package --no-cache-dir 
        cp *.py package/
        (cd package && zip -r ../../app.zip . -x "*__pycache__*" "tests/*")

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: lambda-package
        path: app.zip
        retention-days: 5

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.12.2

    - name: Configure AWS credentials.
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Init (Local State)
      working-directory: terraform
      run: |
        rm -rf .terraform .terraform.lock.hcl
        terraform init -backend=false -reconfigure -input=false -no-color

    - name: Terraform Plan (Local State)
      working-directory: terraform
      run: terraform plan -input=false -no-color -lock=false