name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-test-plan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: pip install -r app/requirements.txt

    - name: Run tests
      run: pytest

    - name: Package Flask app for Lambda
      run: |
        cd app
        pip install -r requirements.txt -t package
        cp app.py package/
        touch package/__init__.py
        cd package
        zip -r ../../app.zip .

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.5

    - name: Configure AWS credentials.
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Init
      run: cd terraform && terraform init

    - name: Terraform Plan
      run: cd terraform && terraform plan
