name: Destroy Resources

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type 'destroy' to confirm"
        required: true
        default: "cancel"

jobs:
  destroy:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'destroy'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.0
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}   

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -reconfigure
      
      - name: Terraform Plan (Destroy)
        working-directory: terraform
        run: terraform plan -destroy

      - name: Terraform Destroy
        working-directory: terraform
        run: terraform destroy -auto-approve
        env:
          TF_WORKSPACE: "default" 

      # 7. Cleanup (optional)
      - name: Delete Local State
        if: always()
        run: |
          rm -f terraform/terraform.tfstate*
          rm -f terraform/.terraform.lock.hcl